---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
<<<<<<< HEAD
        uses: actions/checkout@v3

      - name: Install pylint / pyflakes
        run: |
          sudo apt-get update
          sudo apt-get install --yes pylint pyflakes3
=======
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install test dependencies
        run: pip install -r requirements-test.txt
>>>>>>> upstream/main

      - name: Install pve_exporter
        run: pip install .

      - name: Run pylint
        run: pylint pve_exporter

      - name: Run pyflakes
        run: pyflakes src/pve_exporter
